### ISSUE TITLE
[soapservices] NPE at UpdateScanningStateQuery.<init>

### ISSUE THREAD

**Issue by GoogleCodeExporter** [incad/registrdigitalizace#209]
```
Při chybějícím parametru date (date == null)

java.lang.NullPointerException: Client received an exception from server: null 
Please see the server log to find more detail regarding exact cuase of the 
failure.
    at cz.registrdigitalizace.soapservices.datasource.UpdateScanningStateQuery.<init>(UpdateScanningStateQuery.java:67)
    at cz.registrdigitalizace.soapservices.datasource.DigitizationRegistryDao.updateRecordState(DigitizationRegistryDao.java:51)
    at cz.registrdigitalizace.soapservices.DigitizationRegistry.setRecordState(DigitizationRegistry.java:194)
```

Original issue reported on code.google.com by `pokor...@gmail.com` on 29 Sep 2012 at 9:18

**Comment by MKortus** [comment]
issu bylo uzavřeno již v googleCode. proto uzavírám
